#!/usr/bin/env sh

JARS_PATH=~/.minecraft/versions
VERSION='1.19'
DEST_PATH='minecraft_jar'

JAR_FILE_FILTER='data/minecraft/**'

full_path="$JARS_PATH/$VERSION/$VERSION.jar"

if [ -s $full_path ]
then
    echo "Removing existing $DEST_PATH/$JAR_FILE_FILTER"
    rm -rf $DEST_PATH/$JAR_FILE_FILTER
    echo "Extracting $full_path to $DEST_PATH"
    unzip -q $full_path -d $DEST_PATH

else
    echo "$full_path does not exist"
fi

